{
 "title": "JmeterInflux",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "aggregation", "label": "Aggregation Interval", "query": "1,10,30,60,600,1800,3600" },
   {
    "name": "RUNID",
    "label": "RUN_ID",
    "query": "SHOW TAG VALUES FROM \"requestsRaw\" WITH KEY = \"runId\" WHERE $timeFilter"
   },
   { "name": "dataSource", "query": "influxdb" },
   {
    "name": "request",
    "label": "Request",
    "query": "SHOW TAG VALUES FROM \"requestsRaw\" WITH KEY = \"requestName\" where (\"runId\" =~ /^$RUNID$/) "
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Active users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"startedThreads\") FROM \"virtualUsers\" WHERE  (\"runId\" =~ /^$RUNID$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "threadName" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Transactions Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT  count(\"responseTime\") FROM \"requestsRaw\" WHERE  (\"runId\" =~ /^$RUNID$/ AND \"requestName\" =~ /^$request$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "threadName" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Errors Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT sum(\"errorCount\") FROM \"requestsRaw\" WHERE  (\"runId\" =~ /^$RUNID$/ AND \"requestName\" =~ /^$request$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "threadName" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Overall throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT  count(\"responseTime\")/$aggregation FROM \"requestsRaw\" WHERE  (\"runId\" =~ /^$RUNID$/ AND \"requestName\" =~ /^$request$/) AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "threadName" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT 1 - sum(\"errorCount\")/count(\"responseTime\") FROM \"requestsRaw\" WHERE  (\"runId\" =~ /^$RUNID$/ AND \"requestName\" =~ /^$request$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT sum(\"errorCount\")/count(\"responseTime\") FROM \"requestsRaw\" WHERE (\"runId\" =~ /^$RUNID$/ AND \"requestName\" =~ /^$request$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Synthesis Report",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT count(responseTime) as \"Total Count\", sum(errorCount) as \"Error Count\", mean(responseTime) as Avg, min(responseTime) as Min, median(responseTime) as Median, percentile(responseTime, 90) as \"p90\",percentile(responseTime, 95) as \"p95\",percentile(responseTime, 99) as \"p99\", max(responseTime) as Max, (sum(errorCount)/count(responseTime)) as \"Error Rate\" FROM \"requestsRaw\" WHERE (\"runId\" =~ /^$RUNID$/ AND \"requestName\" =~ /^$request$/) AND $timeFilter GROUP BY requestName fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "runId", "operator": "=~", "value": "/^$RUNID$/" },
      { "condition": "AND", "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Running users over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "NumUsers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualUsers",
     "query": "SELECT mean(\"startedThreads\") FROM \"virtualUsers\" WHERE $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "minActiveThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "runId", "operator": "=~", "value": "/^$RUNID$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "$tag_requestName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "requestName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT count(\"responseTime\")/$aggregation  FROM \"requestsRaw\" WHERE (\"runId\" =~ /^$RUNID$/ AND \"requestName\" =~ /^$request$/) AND $timeFilter GROUP BY time([[aggregation]]s) , \"requestName\"  fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "errors / s" }
   ],
   "targets": [
    {
     "alias": "$tag_requestName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualUsers",
     "query": "SELECT sum(\"errorCount\")/$aggregation FROM \"requestsRaw\" WHERE   (\"runId\" =~ /^$RUNID$/ AND \"requestName\" =~ /^$request$/ ) AND $timeFilter GROUP BY  requestName, time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "startedThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "runId", "operator": "=~", "value": "/^$RUNID$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Times over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_requestName",
     "groupBy": [
      { "params": [ "[[aggregation]]s" ], "type": "time" },
      { "params": [ "requestName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "runId", "operator": "=~", "value": "/^$RUNID$/" },
      { "condition": "AND", "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "alias": "$tag_requestName",
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "select requestName,responseCode,requestHeader,reqPayload,responseHeader,responseData,responseMsg from requestsRaw  WHERE errorCount >0 AND (\"runId\" =~ /^$RUNID$/ AND \"requestName\" =~ /^$request$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "runId", "operator": "=~", "value": "/^$RUNID$/" },
      { "condition": "AND", "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ],
     "timeField": "Timestamp"
    }
   ]
  }
 ]
}